import type { SitePageDataColors } from '@/types/site-page-data';

/** Keys in display order for color circles. */
export const COLOR_KEYS: (keyof SitePageDataColors)[] = [
    'primary',
    'primaryHover',
    'primaryLight',
    'primaryDark',
    'secondary',
    'tertiary',
    'quaternary',
    'quinary',
];

/** 20 preset color palettes (SitePageDataColors). */
export const COLOR_PALETTE_PRESETS: SitePageDataColors[] = [
    {
        primary: '#059669',
        primaryHover: '#047857',
        primaryLight: '#ecfdf5',
        primaryDark: '#065f46',
        secondary: '#0f172a',
        tertiary: '#334155',
        quaternary: '#f8fafc',
        quinary: '#f1f5f9',
    },
    {
        primary: '#dc2626',
        primaryHover: '#b91c1c',
        primaryLight: '#fef2f2',
        primaryDark: '#991b1b',
        secondary: '#1c1917',
        tertiary: '#44403c',
        quaternary: '#fafaf9',
        quinary: '#f5f5f4',
    },
    {
        primary: '#2563eb',
        primaryHover: '#1d4ed8',
        primaryLight: '#eff6ff',
        primaryDark: '#1e40af',
        secondary: '#0f172a',
        tertiary: '#334155',
        quaternary: '#f8fafc',
        quinary: '#f1f5f9',
    },
    {
        primary: '#7c3aed',
        primaryHover: '#6d28d9',
        primaryLight: '#f5f3ff',
        primaryDark: '#5b21b6',
        secondary: '#1e1b4b',
        tertiary: '#3730a3',
        quaternary: '#faf5ff',
        quinary: '#f3e8ff',
    },
    {
        primary: '#ea580c',
        primaryHover: '#c2410c',
        primaryLight: '#fff7ed',
        primaryDark: '#9a3412',
        secondary: '#1c1917',
        tertiary: '#44403c',
        quaternary: '#fafaf9',
        quinary: '#f5f5f4',
    },
    {
        primary: '#0891b2',
        primaryHover: '#0e7490',
        primaryLight: '#ecfeff',
        primaryDark: '#155e75',
        secondary: '#0f172a',
        tertiary: '#334155',
        quaternary: '#f0fdfa',
        quinary: '#ccfbf1',
    },
    {
        primary: '#65a30d',
        primaryHover: '#4d7c0f',
        primaryLight: '#f7fee7',
        primaryDark: '#3f6212',
        secondary: '#1a1a1a',
        tertiary: '#404040',
        quaternary: '#fafafa',
        quinary: '#f5f5f5',
    },
    {
        primary: '#be123c',
        primaryHover: '#9f1239',
        primaryLight: '#fff1f2',
        primaryDark: '#881337',
        secondary: '#1c1917',
        tertiary: '#44403c',
        quaternary: '#fafaf9',
        quinary: '#f5f5f4',
    },
    {
        primary: '#0d9488',
        primaryHover: '#0f766e',
        primaryLight: '#f0fdfa',
        primaryDark: '#115e59',
        secondary: '#134e4a',
        tertiary: '#0f766e',
        quaternary: '#f0fdfa',
        quinary: '#ccfbf1',
    },
    {
        primary: '#4f46e5',
        primaryHover: '#4338ca',
        primaryLight: '#eef2ff',
        primaryDark: '#3730a3',
        secondary: '#1e1b4b',
        tertiary: '#312e81',
        quaternary: '#f5f3ff',
        quinary: '#ede9fe',
    },
    {
        primary: '#ca8a04',
        primaryHover: '#a16207',
        primaryLight: '#fefce8',
        primaryDark: '#854d0e',
        secondary: '#1c1917',
        tertiary: '#44403c',
        quaternary: '#fafaf9',
        quinary: '#fef9c3',
    },
    {
        primary: '#db2777',
        primaryHover: '#be185d',
        primaryLight: '#fdf2f8',
        primaryDark: '#9d174d',
        secondary: '#1f2937',
        tertiary: '#4b5563',
        quaternary: '#fdf2f8',
        quinary: '#fce7f3',
    },
    {
        primary: '#0369a1',
        primaryHover: '#0284c7',
        primaryLight: '#f0f9ff',
        primaryDark: '#075985',
        secondary: '#0c4a6e',
        tertiary: '#0e7490',
        quaternary: '#f0f9ff',
        quinary: '#e0f2fe',
    },
    {
        primary: '#15803d',
        primaryHover: '#166534',
        primaryLight: '#f0fdf4',
        primaryDark: '#14532d',
        secondary: '#052e16',
        tertiary: '#166534',
        quaternary: '#f0fdf4',
        quinary: '#dcfce7',
    },
    {
        primary: '#1d4ed8',
        primaryHover: '#1e40af',
        primaryLight: '#dbeafe',
        primaryDark: '#1e3a8a',
        secondary: '#172554',
        tertiary: '#1e3a8a',
        quaternary: '#eff6ff',
        quinary: '#dbeafe',
    },
    {
        primary: '#6b21a8',
        primaryHover: '#7e22ce',
        primaryLight: '#faf5ff',
        primaryDark: '#581c87',
        secondary: '#3b0764',
        tertiary: '#6b21a8',
        quaternary: '#faf5ff',
        quinary: '#f3e8ff',
    },
    {
        primary: '#b45309',
        primaryHover: '#b45309',
        primaryLight: '#fffbeb',
        primaryDark: '#92400e',
        secondary: '#451a03',
        tertiary: '#78350f',
        quaternary: '#fffbeb',
        quinary: '#fef3c7',
    },
    {
        primary: '#0e7490',
        primaryHover: '#0f766e',
        primaryLight: '#ecfeff',
        primaryDark: '#155e75',
        secondary: '#164e63',
        tertiary: '#0e7490',
        quaternary: '#ecfeff',
        quinary: '#cffafe',
    },
    {
        primary: '#374151',
        primaryHover: '#4b5563',
        primaryLight: '#f3f4f6',
        primaryDark: '#1f2937',
        secondary: '#111827',
        tertiary: '#374151',
        quaternary: '#f9fafb',
        quinary: '#f3f4f6',
    },
    {
        primary: '#059669',
        primaryHover: '#10b981',
        primaryLight: '#d1fae5',
        primaryDark: '#047857',
        secondary: '#064e3b',
        tertiary: '#065f46',
        quaternary: '#ecfdf5',
        quinary: '#d1fae5',
    },
];
